Add simulation service tests
Kraksim/Kraksim pull request #20
Opened 2021-08-21 14:46 UTC by WikKam

2021-08-23 19:12 UTC, Wokstym commented on src/main/kotlin/pl/edu/agh/cs/kraksim/repository/entities/MapEntity.kt
> +    var destinationRoad: RoadEntity
wtf po co tak, skoro i tak bierzemy z tego lane id, wtf

2021-08-23 19:16 UTC, Wokstym commented on src/test/kotlin/pl/edu/agh/cs/kraksim/api/SimulationServiceTest.kt
> +        }
To można załatwić argumentem w `@AutoConfigureTestDatabase(`

2021-08-23 19:19 UTC, Wokstym commented on src/test/kotlin/pl/edu/agh/cs/kraksim/api/factory/nagel/NagelMapFactoryTest.kt
> +        }
to samo

2021-08-23 19:22 UTC, Wokstym commented on src/test/kotlin/pl/edu/agh/cs/kraksim/api/factory/nagel/assertObject/NagelSimulationAssert.kt
> +    fun assertGateways(simulationStateEntity: SimulationStateEntity): NagelSimulationAssert {
no nw czy już nie przesadziłeś troche z tym assertObjectem, bo logika sprawdzana jest obfuskowana przez enigmatyczne `assertGateways`

2021-08-24 19:42 UTC, WikKam commented on src/main/kotlin/pl/edu/agh/cs/kraksim/repository/entities/MapEntity.kt
> +    var destinationRoad: RoadEntity
ciezko mi z palca powiedziec czemu, ale najpewniej tak samo byl problem przy wkladaniu tego do bazy tj skad tego idka wziac jak jeszcze nie zapisany. Ogolnie no ja sie juz wypowiadalem na ten temat i to rozwiazanie z idkami ssie wiec im mniej go tym lepij X D

2021-08-24 19:42 UTC, WikKam commented on src/test/kotlin/pl/edu/agh/cs/kraksim/api/SimulationServiceTest.kt
> +        }
can u provide a snippet? :0

2021-08-24 19:43 UTC, WikKam commented on src/test/kotlin/pl/edu/agh/cs/kraksim/api/factory/nagel/assertObject/NagelSimulationAssert.kt
> +    fun assertGateways(simulationStateEntity: SimulationStateEntity): NagelSimulationAssert {
znaczy no pytanie czy enigmatyczne, po to sie sprowadza w wiekszosci przypadkow do posprawdzania analogicznych pol cnie, jest to na tyle powtarzalne, ze imo essa

2021-08-25 15:53 UTC, Wokstym commented on src/test/kotlin/pl/edu/agh/cs/kraksim/api/factory/nagel/assertObject/NagelSimulationAssert.kt
> +    fun assertGateways(simulationStateEntity: SimulationStateEntity): NagelSimulationAssert {
no niech bedzie, ale akurat to wywołujesz raz XDD

2021-08-25 16:51 UTC, Wokstym requested changes

2021-08-25 16:51 UTC, Wokstym commented on src/test/kotlin/pl/edu/agh/cs/kraksim/api/SimulationServiceTest.kt
> +        val carId = 1
nie uzywasz tego

2021-08-31 15:26 UTC, Wokstym commented on src/test/kotlin/pl/edu/agh/cs/kraksim/api/SimulationServiceTest.kt
> +        val simulation = simulationRepository.findAll().first()
wtedy tu nie trzeba takich hacków robić ze bierzemy pierwszą z brzegu

2021-09-12 11:16 UTC, Wokstym approved these changes

2021-09-12 11:16 UTC, merged