Brake light
Kraksim/Kraksim pull request #49
Opened 2021-11-27 22:08 UTC by miloszgalas

added brake light movement strategy

2021-11-28 09:45 UTC, Wokstym commented on src/main/kotlin/pl/edu/agh/cs/kraksim/simulation/web/request/CreateMovementSimulationStrategyRequest.kt
> +    var breakLightReactionProbability: Double? = null
Walidacja (za pomocą adnotacji, jak np masz wyżej max i min do `slowDownProbability`

2021-11-28 09:46 UTC, Wokstym commented on src/main/kotlin/pl/edu/agh/cs/kraksim/simulation/application/SimulationService.kt
> +                    brakeLightOn = null
moze zamiast tu wszedzie null to zrobić defaultowo null?

2021-11-28 09:47 UTC, Wokstym commented on src/main/kotlin/pl/edu/agh/cs/kraksim/core/movementStrategyUseCase/nagel/state/NagelCar.kt
> +open class NagelCar(
skoro nie ma dziedziczenia to po co to open

2021-11-28 09:54 UTC, Wokstym commented on src/main/kotlin/pl/edu/agh/cs/kraksim/common/exception/ProbabilityMapNotValidException.kt
> +class ProbabilityMapNotValidException : Exception()
Raczej nie robimy osobnej klasy exception dla każdego problemu, to potem jest przechwytywane przez `RestExceptionHandler` który przechwyci pierwszy znajomy typ czyli `Exception` i na fronice się wyświetli coś w stylu `pl.edu.agh.cs.kraksim.common.exception.ProbabilityMapNotValidException`, zamiast tego lepiej użyć jakiegoś istniejącego exceptiona e.g. `IllegalStateException` z message i dodać odpowiedni `@ExceptionHandler` któ®y zwróci wiadomość z odpowiednim kodem i wiadomością (zbliżone do handlera `InvalidSimulationStateConfigurationException` bym zrobił

2021-11-28 10:00 UTC, Wokstym commented on src/main/kotlin/pl/edu/agh/cs/kraksim/common/random/RandomProvider.kt
> +    var probabilityMap: Map<Car, Double>
nw czy jestem wielkim fanem zeby to było varem, zamiast tego Mapa mogłaby być HashMapą i nie byłoby tyle kopiowania przy jakiejkolwiek zmianie

2021-11-28 10:04 UTC, Wokstym commented on src/main/kotlin/pl/edu/agh/cs/kraksim/common/exception/ProbabilityMapNotValidException.kt
> +class ProbabilityMapNotValidException : Exception()
Może nawet zamiast dodawać handler to do listy handlowanych możnaby dodać illegal state

2021-11-28 10:05 UTC, Wokstym commented on src/main/kotlin/pl/edu/agh/cs/kraksim/core/movementStrategyUseCase/brakeLight/BrakeLightMovementSimulationStrategy.kt
> +                if (carInFront.brakeLightOn!! && timeToReachNext > ts) breakLightReactionProbability else if (car.velocity == 0) accelerationDelayProbability else defaultProbability
długie te ify tu, wyżej i na dole, poformatuj je lepiej trochę ze warunki w nowych liniach jak i zawartosc

2021-11-28 10:17 UTC, Wokstym commented on src/main/kotlin/pl/edu/agh/cs/kraksim/core/movementStrategyUseCase/nagel/state/NagelCar.kt
>      var currentLane: NagelLane? = null
weź dodaj proszę coś w stylu 
```kt
    val distanceFromEndOfLane: Int
        get() {
            val result = currentLane!!.cellsCount - positionRelativeToStart - 1
            if(result < 0) throw IllegalStateException("Car position is greater than lane length, carId=$id, position=$positionRelativeToStart, currentLaneId=${currentLane?.id}")
            return result
        }
        ```

2021-11-28 10:17 UTC, Wokstym commented on src/main/kotlin/pl/edu/agh/cs/kraksim/core/movementStrategyUseCase/nagel/state/NagelCar.kt
>      var currentLane: NagelLane? = null
bo w sumie rpzypał może być

2021-11-28 10:20 UTC, Wokstym commented on src/main/kotlin/pl/edu/agh/cs/kraksim/core/movementStrategyUseCase/brakeLight/BrakeLightMovementSimulationStrategy.kt
> +                if (car.velocity > distanceToMoveOnCurrentLane) car.gps.getTargetLaneInNextRoad(this::getLane)
brakuje ci tu warunku co jezeli pas się konczy wcześniej albo wgl z tego pasa nie da się wjechać na dany pas? w sloLastCar jest taki if 
```
            val freeSpaceInCarPath =
                if (endNode.canGoThrough(lane)) {
                    lastCar.distanceFromEndOfLane + destinationLane.getFreeSpaceInFront()
                } else {
                    lastCar.distanceFromEndOfLane
                }
```

2021-11-28 10:23 UTC, Wokstym commented on src/main/kotlin/pl/edu/agh/cs/kraksim/core/movementStrategyUseCase/brakeLight/BrakeLightMovementSimulationStrategy.kt
> +                if (car.velocity > distanceToMoveOnCurrentLane) car.gps.getTargetLaneInNextRoad(this::getLane)
odrazu też tutaj jest osobna metoda  w `Nagel simulationStrategy`: `getTargetLane`, zmien sb ją z private i użyj tutaj, troche czytelniej zawsze

2021-11-28 10:25 UTC, Wokstym commented on src/test/kotlin/pl/edu/agh/cs/kraksim/common/MockRandomProvider.kt
> +    override var probabilityMap: Map<Car, Double> = emptyMap()
zrób też wgl osobną metodkę do dawania tego propability i wtedy ta zmienna może być prywatna (zasada odpowiedzialności cos ta któreś z SOLID xD)

2021-11-28 10:27 UTC, Wokstym commented on src/main/kotlin/pl/edu/agh/cs/kraksim/core/movementStrategyUseCase/brakeLight/BrakeLightMovementSimulationStrategy.kt
> +            val carOnNextRoad: Car? = car.gps.getTargetLaneInNextRoad(this::getLane).cars.getOrNull(0)
tu zrób na końcu `as NagelCar?` wtedy if bedzie czystszy

2021-11-28 10:30 UTC, Wokstym commented on src/main/kotlin/pl/edu/agh/cs/kraksim/core/movementStrategyUseCase/brakeLight/BrakeLightMovementSimulationStrategy.kt
> +                if ((carOnNextRoad as NagelCar?)?.brakeLightOn == true && timeToReachNext > ts) breakLightReactionProbability else if (car.velocity == 0) accelerationDelayProbability else defaultProb
wyżej dałeś `carInFront.brakeLightOn!!` tutaj luźniejszy warunek, imo ten z wyżej lepszy bo wyjebie przy zlej konfiguracji

2021-11-28 10:32 UTC, Wokstym commented on src/main/kotlin/pl/edu/agh/cs/kraksim/core/movementStrategyUseCase/brakeLight/BrakeLightMovementSimulationStrategy.kt
> +                if (car.velocity > distanceToMoveOnCurrentLane) car.gps.getTargetLaneInNextRoad(this::getLane)
i wydziel ją do zmiennej, wywołujesz to niżej też

2021-11-28 10:40 UTC, Wokstym commented on src/main/kotlin/pl/edu/agh/cs/kraksim/trafficState/application/MovementSimulationStrategyFactory.kt
> +        requireNotNull(entity.threshold)
`val threshold = requireNotNull(entity.threshold)`
wtedy nie musisz dawać wykrzykników niżej, analogicznie z pozostalymi zrób (to be safe)

2021-11-28 10:42 UTC, Wokstym requested changes
poprawki

2021-11-28 11:07 UTC, miloszgalas commented on src/main/kotlin/pl/edu/agh/cs/kraksim/simulation/web/request/CreateMovementSimulationStrategyRequest.kt
> +    var breakLightReactionProbability: Double? = null
a jak to zadzaiała jak będzie null?

2021-11-28 12:32 UTC, Wokstym commented on src/main/kotlin/pl/edu/agh/cs/kraksim/simulation/web/request/CreateMovementSimulationStrategyRequest.kt
> +    var breakLightReactionProbability: Double? = null
Tak tzn max waliduje wartość jezeli nie jest nullem, wiec przejdzie chyba

2021-11-28 12:34 UTC, Wokstym commented on src/main/kotlin/pl/edu/agh/cs/kraksim/simulation/web/request/CreateMovementSimulationStrategyRequest.kt
> +    var breakLightReactionProbability: Double? = null
+ jeszcze pomyslałem teraz ze dodaj dodatkową walidacje w `SimulationService` masz taka funkcje `validateState(simulationState: SimulationState, simulationEntity: SimulationEntity)`  i wniej zrob ze jezeli state jest break light to te 3 wartości nie mogą być null

2021-11-30 13:42 UTC, miloszgalas commented on src/main/kotlin/pl/edu/agh/cs/kraksim/simulation/application/SimulationService.kt
> +                    brakeLightOn = null
jest defaultowo null ale jak ustawiłem defaulta to nie pousuwałęm wszędzie

2021-11-30 15:32 UTC, miloszgalas commented on src/main/kotlin/pl/edu/agh/cs/kraksim/core/movementStrategyUseCase/brakeLight/BrakeLightMovementSimulationStrategy.kt
> +                if (car.velocity > distanceToMoveOnCurrentLane) car.gps.getTargetLaneInNextRoad(this::getLane)
ale to jest jednopasmowe, chcemy się tym tu zajmować?

2021-12-04 00:41 UTC, Wokstym commented on src/main/kotlin/pl/edu/agh/cs/kraksim/core/movementStrategyUseCase/brakeLight/BrakeLightMovementSimulationStrategy.kt
> +                if (car.velocity > distanceToMoveOnCurrentLane) car.gps.getTargetLaneInNextRoad(this::getLane)
hm no dobra

2021-12-04 09:22 UTC, Wokstym approved these changes

2021-12-04 09:23 UTC, merged